### ISSUE TITLE
count variable in coverReport() not initialized

### ISSUE THREAD

**Issue by yoowoo** [oleorhagen/gobinarycoverage#1]
@oleorhagen really like this! Just noticed count is not set, just declared https://github.com/oleorhagen/gobinarycoverage/blob/2bb04afbaca5f6941d7d91b113fa9f5140a2d81a/gobinarycoverage.go#L457

I'd also suggest to print own messages like https://github.com/oleorhagen/gobinarycoverage/blob/2bb04afbaca5f6941d7d91b113fa9f5140a2d81a/gobinarycoverage.go#L477 to stdout and adding a new line in https://github.com/oleorhagen/gobinarycoverage/blob/2bb04afbaca5f6941d7d91b113fa9f5140a2d81a/gobinarycoverage.go#L454 so the result files of `gobinarycoverage` has valid coverage file format and one can run `go tool cover -func ./coverageresult.out`

Again - awesome job, thanks for sharing!

**Comment by oleorhagen** [comment]
@yoowoo Hi, and thanks for your interest in this :)

All your suggestions look sensible, and I will add them soon, unless you feel like making a PR? :1st_place_medal: 

Also, I'm curious how you stumbled upon this, why you need it, and how it was setting it up when new to the project?

**Comment by yoowoo** [comment]
@oleorhagen I've realized that this piece of code is also in https://github.com/mendersoftware/gobinarycoverage and since it has all the suggestions implemented, I've switched to it. Seems you are author of both, so I assume it is ok ;).

**Comment by oleorhagen** [comment]
@yoowoo haha, great! Yes, this was just a workground until this was ready for upstream.

I will synchronize master here though, just in case someone else is stumbling upon this first, just like you did :)

**Comment by oleorhagen** [comment]
Fix is present in the mendersoftware binarycoverage fork. Closing and syncing the branches :)
